"""Engine selector for Gaming Mode.

This module is deliberately *not* an injector.  Moon and Luma are independent
backends under ``lt.engines`` and each backend owns its dependency layout,
updates, and Steam hook/injection environment.  The manager only persists the
selected backend and installs a tiny one-shot selector at the already-working
EngineTest Gaming Mode entry point.
"""
from __future__ import annotations

import json
import os
import stat
import time
from typing import Any, Dict

from .engines import MoonEngine, LumaEngine
from .logger import logger
from .paths import get_user_home

STATE_DIR = os.path.join(get_user_home(), ".config", "slsdeck")
STATE_PATH = os.path.join(STATE_DIR, "engine.json")
ENGINE_ROOT = os.path.join(get_user_home(), ".local", "share", "slsdeck", "engines")
DISPATCHER = os.path.join(get_user_home(), ".local", "share", "SLSsteam", "path", "steam")

_MOON = MoonEngine()
_LUMA = LumaEngine()


def _chown(path: str) -> None:
    try:
        from .utils import chown_to_user
        chown_to_user(path, recursive=False)
    except Exception:
        pass


def _write_json(path: str, value: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = f"{path}.tmp.{os.getpid()}"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(value, f, indent=2, sort_keys=True)
        f.write("\n")
        f.flush()
        try: os.fsync(f.fileno())
        except Exception: pass
    os.replace(tmp, path)
    _chown(path)


def selected_engine() -> str:
    try:
        with open(STATE_PATH, "r", encoding="utf-8") as f:
            selected = json.load(f).get("selected")
        return selected if selected in ("moon", "luma") else "moon"
    except Exception:
        return "moon"


def _backend(name: str):
    return _MOON if name == "moon" else _LUMA


def _write_engine_launcher(name: str) -> str:
    """Ask the backend for its own injection contract and materialize it as an
    engine-owned launcher. The selector never interprets LD_AUDIT/LD_PRELOAD.
    """
    backend = _backend(name)
    root = backend.ROOT
    path = os.path.join(root, "launch-steam")
    env = backend.launcher_environment()
    os.makedirs(root, exist_ok=True)
    lines = ["#!/bin/sh", "# Generated by the engine backend; do not edit the selector.", "unset LD_AUDIT LD_PRELOAD"]
    for key, value in env.items():
        # Backend values are trusted local absolute paths. Quote defensively for
        # shell execution; no user-controlled content is interpolated here.
        safe = value.replace("'", "'\\''")
        lines.append(f"export {key}='{safe}'")
    lines += ["exec steam \"$@\"", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    _chown(path)
    return path


def ensure_dispatcher() -> Dict[str, Any]:
    """Install only the engine selector at the existing Gaming Mode entry point.

    The selector contains no engine-specific injection code. It simply execs the
    selected backend's own launcher. This is the boundary that lets Moon and Luma
    be upgraded independently.
    """
    try:
        moon_launcher = _write_engine_launcher("moon") if _MOON.installed() else os.path.join(_MOON.ROOT, "launch-steam")
        luma_launcher = _write_engine_launcher("luma") if _LUMA.installed() else os.path.join(_LUMA.ROOT, "launch-steam")
        os.makedirs(os.path.dirname(DISPATCHER), exist_ok=True)
        script = f'''#!/bin/sh
# EngineTest selector. It contains no injection implementation.
ENGINE_FILE="$HOME/.config/slsdeck/engine.json"
engine="moon"
if [ -r "$ENGINE_FILE" ]; then
  engine="$(sed -n 's/.*"selected"[[:space:]]*:[[:space:]]*"\\(moon\\|luma\\)".*/\\1/p' "$ENGINE_FILE" | head -n1)"
fi
if [ "$engine" = "luma" ] && [ -x '{luma_launcher}' ]; then
  exec '{luma_launcher}' "$@"
fi
if [ -x '{moon_launcher}' ]; then
  exec '{moon_launcher}' "$@"
fi
exec steam "$@"
'''
        with open(DISPATCHER, "w", encoding="utf-8") as f:
            f.write(script)
        os.chmod(DISPATCHER, 0o755)
        _chown(DISPATCHER)
        return {"success": True, "path": DISPATCHER}
    except Exception as exc:
        logger.warn(f"EngineTest: dispatcher setup failed: {exc}")
        return {"success": False, "error": str(exc)}


def status() -> Dict[str, Any]:
    return {
        "success": True,
        "selected": selected_engine(),
        "moonInstalled": _MOON.installed(),
        "lumaInstalled": _LUMA.installed(),
        "dispatcher": os.path.isfile(DISPATCHER),
        "dispatcherPath": DISPATCHER,
        "moon": _MOON.status(),
        "luma": _LUMA.status(),
    }


def install_luma() -> Dict[str, Any]:
    # Luma owns its entire dependency update/install path.
    result = _LUMA.install()
    if result.get("success"):
        ensure_dispatcher()
    return result


def update_luma() -> Dict[str, Any]:
    return install_luma()


def set_engine(engine: str) -> Dict[str, Any]:
    if engine not in ("moon", "luma"):
        return {"success": False, "error": "Unknown engine"}
    backend = _backend(engine)
    if not backend.installed():
        return {"success": False, "error": f"{engine} engine is not installed"}
    prepared = backend.prepare()
    if not prepared.get("success", False):
        return prepared
    r = ensure_dispatcher()
    if not r.get("success"):
        return r
    _write_json(STATE_PATH, {"selected": engine, "changedAt": int(time.time())})
    return {"success": True, "selected": engine, "restartRequired": True}


def prepare() -> Dict[str, Any]:
    """Refresh backend-owned launchers without changing the selected engine."""
    try:
        _MOON.prepare()
        if _LUMA.installed():
            _LUMA.prepare()
        return ensure_dispatcher()
    except Exception as exc:
        logger.warn(f"EngineTest: engine prepare failed: {exc}")
        return {"success": False, "error": str(exc)}
